# Generated by Django 3.0.5 on 2020-04-12 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTypeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название проекта')),
                ('conf', models.TextField(verbose_name='Конфиг текст')),
            ],
            options={
                'verbose_name': 'Тип проекта',
                'verbose_name_plural': 'Типы проектов',
            },
        ),
        migrations.CreateModel(
            name='DomainModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, verbose_name='Название домена (ex. www.google.com)')),
                ('path', models.CharField(max_length=225, verbose_name='Путь к проекту')),
                ('static', models.CharField(max_length=120, verbose_name='Название статической папке')),
                ('status', models.PositiveIntegerField(choices=[(0, 'Не активен'), (1, 'Активен')], default=0, verbose_name='Статус сайта')),
                ('server', models.PositiveIntegerField(choices=[(0, 'Apache'), (1, 'Nginx')], default=0, verbose_name='Типы сервера')),
                ('projectType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ProjectTypeModel', verbose_name='Типы проекта')),
            ],
            options={
                'verbose_name': 'Сайт',
                'verbose_name_plural': 'Сайты',
            },
        ),
    ]
